// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BroadVoicePOC.DataAccess.Models
{
    public partial class Salesperson
    {
        public Salesperson()
        {
            Sales = new HashSet<Sale>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Sale> Sales { get; set; }
    }
}