// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BroadVoicePOC.DataAccess.Models
{
    public partial class Sale
    {
        public int Id { get; set; }
        public int SalespersonId { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public DateTime? Date { get; set; }
        public decimal? Price { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Salesperson Salesperson { get; set; }
    }
}