// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace BroadVoicePOC.Model
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class SpWho3ReturnModel
    {
        public System.Int16 SPID { get; set; }
        public System.Int32? BlkBy { get; set; }
        public System.Int32 ElapsedMS { get; set; }
        public System.Int32 CPU { get; set; }
        public System.Int64? IOReads { get; set; }
        public System.Int64 IOWrites { get; set; }
        public System.Int32? Executions { get; set; }
        public System.String CommandType { get; set; }
        public System.String LastWaitType { get; set; }
        public System.String ObjectName { get; set; }
        public System.String SQLStatement { get; set; }
        public System.String STATUS { get; set; }
        public System.String Login { get; set; }
        public System.String Host { get; set; }
        public System.String DBName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.String Protocol { get; set; }
        public System.String transaction_isolation { get; set; }
        public System.Int32? ConnectionWrites { get; set; }
        public System.Int32? ConnectionReads { get; set; }
        public System.String ClientAddress { get; set; }
        public System.String Authentication { get; set; }
        public System.DateTime? DatetimeSnapshot { get; set; }
        public System.Byte[] plan_handle { get; set; }
    }

}
// </auto-generated>
